# gitlab-ci

variables:
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=./.m2/repository"

cache:
  paths:
    - ./.m2/repository

stages:
  - test
  - build
  - release

before_script:
  - curl -s toast.sh/install-v3 | bash

test:
  stage: test
  image: maven:latest
  script:
    - mvn test

build:
  stage: build
  image: maven:latest
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/

release:
  stage: release
  image: nalbam/builder:awscli
  script:
    - ~/toaster/toast.sh release bucket public
  artifacts:
    paths:
      - target/

after_script:
  - ls -alh target
