# gitlab-ci

variables:
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=./.m2/repository"

cache:
  paths:
    - ./.m2/repository
  key: "$CI_BUILD_REF_NAME"

stages:
  - build
  - deploy

before_script:
  - curl -s toast.sh/install-v3 | bash

build:
  stage: build
  image: maven:latest
  script:
    - ~/toaster/toast.sh build version
    - mvn package
  artifacts:
    paths:
      - target/

deploy:
  stage: deploy
  image: python:latest
  script:
    - pip install awscli
    - ~/toaster/toast.sh releases bucket

after_script:
  - ls -alh target
