# .travis.yml
language: java

jdk:
  - oraclejdk7

script:
  - mvn -s settings.xml clean deploy

after_success:
  - mvn -s settings.xml cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
