# .travis.yml
language: java

jdk:
  - oraclejdk7

install:
  - mvn -s settings.xml -version -B

script:
  - mvn -s settings.xml clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
