# .travis.yml
language: java

jdk:
  - oraclejdk7

script:
  mvn deploy --settings settings.xml

after_success:
  mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:cobertura
