# .travis.yml
language: java

jdk:
  - oraclejdk7

install:
  - mvn -s settings.xml clean install

script:
  - mvn -s settings.xml cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
