#
# CircleCI 2.0
#
version: 2
jobs:
  build:
    docker:
      - image: nalbam/builder:maven
    steps:
      - checkout
      - run: mvn package
      - persist_to_workspace:
          root: target
          paths:
            - *.jar
      - store_artifacts:
          path: target/*.jar

workflows:
  version: 2
  java:
    jobs:
      - build
