#
# CircleCI 2.0
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-
      - run: mvn package
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - store_artifacts:
          path: target
#      - persist_to_workspace:
#          root: /tmp/target
#          paths:
#            - *
  deploy:
    docker:
      - image: nalbam/builder:python
    steps:
      - checkout
      - attach_workspace:
          at: target
      - run: aws s3 sync target/ s3://repo.nalbam.com/maven/${CIRCLE_PROJECT_REPONAME}/ --acl public-read

workflows:
  version: 2
  maven:
    jobs:
      - build
#      - deploy:
#          requires:
#            - build
